name: Cypress test 
on: [push]
jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Cypress run with specific specs
          uses: cypress-io/github-action@v5
          with:
              spec: "cypress/integration/examples/api testing/*.js"
          