name: Cypress test 
on: [push]
jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checout@v3
        - name: Cypress run
          uses: cypress-io/github-action@v5